spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/engineer
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher