spring:
  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/engineer
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL_USERNAME}
    password: ${GMAIL_PASSWORD}
    default-encoding: UTF-8
    test-connection: on
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
